### ISSUE TITLE
A studyset with 0 terms causes "500 Internal Server Error" on views/studyset.html

### ISSUE THREAD

**Issue by ehanahamed** [ehanahamed/quizfreely#30]
**Description**
Users can successfully create a studyset with zero terms. The set is correctly written into our database, and other things like searching for it or displaying it in users' dashboards all work correctly.

However, trying to view the studyset by going to it's studyset page (from the dashboard, or search results, or anywhere) throws an error code 500.

This is because `quizfreely/web/views/studyset.html` uses properties under `studyset.data.terms`, like `studyset.data.terms[0][1]` for example, without checking if `studyset.data.terms` or `studyset.data.terms[0]` exist.

**Comment by SagarChandra07** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by ehanahamed** [comment]
This issue has been fixed!
