### ISSUE TITLE
Long studyset titles and display names overflow

### ISSUE THREAD

**Issue by ehanahamed** [ehanahamed/quizfreely#46]
**Description**
Studyset titles and user display names overflow the width of their containers if they are "one word" long. Long titles with spaces between words get newlines like they're supposed to, but single words overflow.

**Screenshots**
![image of overflowing display name](https://github.com/user-attachments/assets/43c35c6f-605d-4956-9848-43c143b315e1)

**Comment by ehanahamed** [comment]
Fixed & released in v0.27.1 👍

**Comment by NulledBird** [comment]
how would one even stumble upon this
