### ISSUE TITLE
Users can create blank studyset titles and usernames

### ISSUE THREAD

**Issue by ehanahamed** [ehanahamed/quizfreely#47]
**Description**
Users can create blank studyset titles which will make their links inaccessible. They can also make blank display names. However, that isn't as big of a deal as inaccessible, invisible, studysets.

**Screenshots**
![image of empty studyset link box with no text](https://github.com/user-attachments/assets/918cc393-2946-4025-a51c-1551d80aa33c)

**Comment by ehanahamed** [comment]
This has been fixed (and released/pushed-to-production in v0.27.1)

**Comment by NulledBird** [comment]
how would one even stumble upon this
